# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='creator',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='creation', to='login.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secret',
            name='like',
            field=models.ManyToManyField(related_name='liked', to='login.User'),
        ),
    ]
