# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20170322_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='login.User'),
        ),
    ]
